import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'

export default function AuthorizationPage(): JSX.Element {
  return (
    <div className={styles.container}>
      <Head>
        <title>Authorization</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Here you will find the quick links for registration</h1>

        <p className={styles.description}>Bellow you have some sections to check our examples</p>

        <div className={styles.grid}>
          <Link href="/register">
            <a className={styles.card}>
              <h2>Registration &rarr;</h2>
              <p>See the complete registration flow, login, reset and set password</p>
            </a>
          </Link>
          <Link href="/dashboard">
            <a className={styles.card}>
              <h2>dashboard &rarr;</h2>
              <p>See the complete registration flow, login, reset and set password</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
